sudo: true
language: php

env:
    global:
        - CHECK_PHP_SYNTAX="no"

matrix:
    fast_finish: true
    include:
        - php: 7.0
        - php: 7.1
          env: CHECK_PHP_SYNTAX="yes"

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - sudo add-apt-repository -y ppa:git-core/ppa
    - sudo apt-get update && sudo apt-get install git-man && sudo apt-get install -y git
    - git --version
    - phpenv config-rm xdebug.ini || true
    - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
    - composer global require kherge/box --prefer-dist --no-interaction --optimize-autoloader
    - composer update --prefer-dist --no-interaction --optimize-autoloader

script:
    - phpunit --exclude-group infra
    - if [[ "$CHECK_PHP_SYNTAX" == "yes" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --dry-run --no-interaction --diff; fi;
